// apps/web/src/ui/kitchen/CameraWidget.svelte
<script lang="ts">
	let stream = $state<MediaStream | null>(null);
	let capturedImage = $state<string | null>(null);
	let error = $state<string | null>(null);
	let videoElement: HTMLVideoElement | null = $state(null);
	let hasCamera = $state(true);

	async function startCamera() {
		try {
			const mediaStream = await navigator.mediaDevices.getUserMedia({
				video: { facingMode: 'environment' }
			});
			stream = mediaStream;
			error = null;
			if (videoElement) {
				videoElement.srcObject = mediaStream;
			}
		} catch (err) {
			hasCamera = false;
			error = 'Camera not available. Please grant camera permissions.';
		}
	}

	function stopCamera() {
		if (stream) {
			stream.getTracks().forEach((track) => track.stop());
			stream = null;
		}
	}

	function capturePhoto() {
		if (!videoElement) return;
		const canvas = document.createElement('canvas');
		canvas.width = videoElement.videoWidth;
		canvas.height = videoElement.videoHeight;
		const ctx = canvas.getContext('2d');
		if (ctx) {
			ctx.drawImage(videoElement, 0, 0);
			capturedImage = canvas.toDataURL('image/jpeg');
		}
	}

	$effect(() => {
		startCamera();
		return () => stopCamera();
	});
</script>

<div class="camera-widget">
	{#if error}
		<p class="error">{error}</p>
	{:else if capturedImage}
		<img src={capturedImage} alt="Captured" class="captured" />
	{:else}
		<video bind:this={videoElement} autoplay playsinline class="preview"></video>
	{/if}

	{#if !capturedImage && hasCamera}
		<button onclick={capturePhoto} disabled={!stream}>Capture</button>
	{/if}

	{#if capturedImage}
		<button onclick={() => (capturedImage = null)}>Retake</button>
	{/if}
</div>

<style>
	.camera-widget {
		display: flex;
		flex-direction: column;
		gap: 1rem;
		align-items: center;
	}

	.preview,
	.captured {
		width: 100%;
		max-width: 400px;
		border-radius: 8px;
	}

	.error {
		color: #d32f2f;
	}

	button {
		padding: 0.5rem 1rem;
		background: #1976d2;
		color: white;
		border: none;
		border-radius: 4px;
		cursor: pointer;
	}

	button:disabled {
		background: #ccc;
		cursor: not-allowed;
	}
</style>

// apps/web/src/ui/kitchen/CameraWidget.tsx
import { useEffect, useRef, useState } from 'react'

export default function CameraWidget() {
  const videoRef = useRef<HTMLVideoElement>(null)
  const [stream, setStream] = useState<MediaStream | null>(null)
  const [capturedImage, setCapturedImage] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    navigator.mediaDevices
      .getUserMedia({ video: { facingMode: 'environment' } })
      .then((s) => {
        setStream(s)
        if (videoRef.current) videoRef.current.srcObject = s
      })
      .catch(() => setError('Camera not available. Please grant camera permissions.'))

    return () => {
      stream?.getTracks().forEach((t) => t.stop())
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  function capturePhoto() {
    const video = videoRef.current
    if (!video) return
    const canvas = document.createElement('canvas')
    canvas.width = video.videoWidth
    canvas.height = video.videoHeight
    canvas.getContext('2d')?.drawImage(video, 0, 0)
    setCapturedImage(canvas.toDataURL('image/jpeg'))
  }

  return (
    <div className="camera-widget">
      {error ? (
        <p className="error">{error}</p>
      ) : capturedImage ? (
        <img src={capturedImage} alt="Captured" className="camera-preview" />
      ) : (
        <video ref={videoRef} autoPlay playsInline className="camera-preview" />
      )}
      {!capturedImage && !error && (
        <button className="btn-primary" onClick={capturePhoto} disabled={!stream}>Capture</button>
      )}
      {capturedImage && (
        <button className="btn-primary" onClick={() => setCapturedImage(null)}>Retake</button>
      )}
    </div>
  )
}
